echo "BUILD MAIN JSON DOCS AND EXPORT JS FILES"
jsdoc .\ -c jsdoc.json --verbose --debug > "jsdoc_Output.log"
echo "COMPILE MD\CORE"
jsdoc2md ".\\js\\core\\Math.ahk.js" > ".\\MD\\core\\MATH.md"
jsdoc2md ".\\js\\core\\log.ahk.js" > ".\\MD\\core\\log.md"
jsdoc2md ".\\js\\core\\adaptive_control.ahk.js" > ".\\MD\\core\\adaptive_control.md"
jsdoc2md ".\\js\\core\\IniSettings.ahk.js" > ".\\MD\\core\\IniSettings.md"
jsdoc2md ".\\js\\core\\Rectangle.ahk.js" > ".\\MD\\core\\Rectangle.md"
jsdoc2md ".\\js\\core\\RectPlugin.ahk.js" > ".\\MD\\core\\RectPlugin.md"
jsdoc2md ".\\js\\core\\Roblox.ahk.js" > ".\\MD\\core\\Roblox.md"
jsdoc2md ".\\js\\core\\timer.ahk.js" > ".\\MD\\core\\timer.md"
echo "COMPILE MD\PLUGINS"
jsdoc2md ".\\js\\plugins\\auto crafter.ahk.js" > ".\\MD\\plugins\\auto_crafter.md"
jsdoc2md ".\\js\\plugins\\biomes.ahk.js" > ".\\MD\\plugins\\biomes.md"
jsdoc2md ".\\js\\plugins\\PluginManager.ahk.js" > ".\\MD\\plugins\\PluginManager.md"
jsdoc2md ".\\js\\plugins\\snowman.pathing.ahk.js" > ".\\MD\\plugins\\snowman.pathing.md"
jsdoc2md ".\\js\\plugins\\StrangeController.ahk.js" > ".\\MD\\plugins\\StrangeController.md"
echo "COMPILE MD\."
jsdoc2md ".\\js\\fishSol.ahk.js" > ".\\MD\\fishSol.md"
jsdoc2md ".\\js\\LaunchMacro.ahk.js" > ".\\MD\\LaunchMacro.md"
echo "done!"
